// Authored listening clips are spoken by the browser's English voice.
const LISTENING_LESSONS=[
['Explorer','Everyday English','Announcement: The school library will close at two o’clock today. Please return your books before lunch.','What time will the library close?',['At noon','At two o’clock','At four o’clock','At six o’clock'],1,'Pengumuman menyebut tutup pukul two o’clock. Jangan tertukar dengan batas pengembalian buku sebelum makan siang.'],
['Explorer','Greeting','Hello, my name is Lily. I am new in this class. It is nice to meet you.','What is Lily doing?',['Saying goodbye forever','Giving directions','Introducing herself','Ordering lunch'],2,'Lily menyebut nama dan bahwa ia murid baru. Ia sedang memperkenalkan diri.'],
['Explorer','Family tree','My name is Sam. My mother has a brother called Uncle Tom. Tom has a daughter named Amy.','How is Amy related to Sam?',['She is his cousin','She is his aunt','She is his mother','She is his grandmother'],0,'Amy adalah anak dari paman Sam, sehingga hubungan mereka adalah sepupu.'],
['Explorer','Gratitude','You dropped your notebook, Ben. Here it is. Thank you for picking it up, Maya. You’re welcome.','Why does Ben thank Maya?',['She bought him lunch','She wrote his homework','She called his teacher','She picked up his notebook'],3,'Ben berterima kasih karena Maya mengambil buku catatannya yang jatuh.'],
['Challenger','Everyday English','The football match was planned for Saturday morning. Because heavy rain is expected, it will now take place on Sunday afternoon.','When will the match take place?',['Saturday morning','Saturday afternoon','Sunday afternoon','Sunday morning'],2,'Perhatikan jadwal baru setelah perubahan: Sunday afternoon. Jadwal pertama sudah tidak berlaku.'],
['Challenger','Communication & social functions','I would love to join your picnic, but I have promised to help my grandmother that day. Thank you for inviting me.','What is the speaker doing?',['Accepting the invitation','Politely declining an invitation','Cancelling everyone’s picnic','Asking for a new grandmother'],1,'Pembicara berterima kasih tetapi memiliki janji lain. Ia menolak undangan dengan sopan.'],
['Challenger','Everyday English','Go past the bakery, turn left at the bridge, and you will see the museum opposite the post office.','What should you do at the bridge?',['Turn left','Turn right','Stop at the bakery','Enter the post office'],0,'Instruksi menyebut turn left at the bridge. Museum adalah tujuan akhir, bukan tindakan di jembatan.'],
['Challenger','Communication & social functions','I understand your idea, but some pupils cannot stay after school. Could we hold the meeting during lunch instead?','Why does the speaker suggest a lunchtime meeting?',['The classroom has no windows','Nobody likes lunch','School starts in the evening','Some pupils cannot stay after school'],3,'Usulan waktu baru dibuat agar murid yang tidak bisa tinggal setelah sekolah tetap dapat ikut.'],
['Champion','Communication & social functions','We could print a poster for every classroom. However, the printer has very little ink. Let’s put one poster on the noticeboard and send the details to each class teacher.','Why does the speaker change the plan?',['The teachers dislike posters','The printer has little ink','There are no classrooms','The noticeboard is broken'],1,'Keterbatasan tinta mendorong alternatif: satu poster dan informasi kepada guru.'],
['Champion','Everyday English','The museum ticket includes the main exhibition, but the planetarium show requires a separate ticket. Children under six may enter the main exhibition free.','Which statement is supported by the announcement?',['Every visitor enters every room for free','A museum ticket includes the planetarium show','The planetarium needs a separate ticket','Children under six must buy two tickets'],2,'Pengumuman membedakan pameran utama dan planetarium. Tiket planetarium harus dibeli terpisah.'],
['Champion','Communication & social functions','Our first model fell over when we added the roof. We widened the base, but it still leaned to one side. Finally, we balanced the weight, and the model stood firmly.','What finally made the model stable?',['Balancing the weight','Removing every wall','Making the roof heavier on one side','Painting the base'],0,'Kata finally menandai perubahan terakhir yang berhasil: menyeimbangkan berat.'],
['Champion','Everyday English','This survey asked only members of the swimming club about their favourite sport. Most chose swimming. We should ask pupils from other clubs before making a claim about the whole school.','Why should more pupils be asked?',['The school has no swimming club','Every answer must be changed','Swimming is not a sport','The original group may not represent the whole school'],3,'Responden hanya berasal dari klub renang. Sampelnya belum mewakili seluruh sekolah.']
];
LISTENING_LESSONS.forEach((r,i)=>QUESTIONS.push({id:'listening-'+String(i+1).padStart(2,'0'),topic:'social',tag:r[1],level:r[0],transcript:r[2],prompt:r[3],options:r[4],answer:r[5],explanation:r[6],passage:'',listening:true,hint:'Dengarkan kata penanda waktu, perubahan rencana, alasan, atau hubungan orang. Putar ulang dengan kecepatan lebih lambat jika perlu.'}));
const SPEAKING_PROMPTS=[
{id:'greeting',title:'Meet a new friend',text:'Hello! My name is Alex. It is nice to meet you. What do you like to do after school?',tip:'Berhenti sebentar setelah sapaan. Naikkan intonasi secara wajar saat bertanya.'},
{id:'help',title:'Ask for help',text:'Excuse me. Could you explain this question again, please? I understand the first part, but I need help with the ending.',tip:'Ucapkan permintaan dengan ramah. Tekankan bagian yang ingin kamu pahami.'},
{id:'thanks',title:'Say a meaningful thank you',text:'Thank you for helping me with my project. Your suggestion made the story much clearer. I really appreciate your time.',tip:'Pisahkan kalimat menjadi kelompok pendek agar mudah dipahami.'},
{id:'story',title:'Tell a short story',text:'Yesterday, I found a small bird near our garden. I asked an adult for help. We watched from a distance until the bird flew away.',tip:'Perhatikan akhiran kata kerja lampau. Baca runtut tanpa perlu terburu-buru.'},
{id:'opinion',title:'Explain your opinion',text:'I think our class should plant more trees. They can give us shade and provide homes for birds. What do you think?',tip:'Beri penekanan pada alasan. Akhiri dengan pertanyaan yang mengajak berdiskusi.'},
{id:'kindness',title:'Disagree kindly',text:'I see what you mean, but I have another suggestion. Could we try both ideas and compare the results together?',tip:'Gunakan nada hangat. Tujuannya berbagi ide, bukan memenangkan perdebatan.'}
];
