/* Interactive tasks also have a standard multiple-choice form for existing exams. */
const ACTIVE_TASKS={},QUEST_WORDS=[];
(()=>{
 const levels=['Explorer','Challenger','Champion'];
 function add(kind,n,topic,tag,prompt,options,answer,explanation,data,passage=''){
  const id='interactive-'+kind+'-'+n,level=levels[(n-1)%3];
  ACTIVE_TASKS[id]={id,kind,...data};QUESTIONS.push({id,topic,tag,level,prompt,options,answer,explanation,passage,activity:kind});
 }
 const orders=[
 ['Simple past tense',['We','visited','the museum','yesterday.'],'Yesterday menyatakan kejadian selesai di masa lalu; visited adalah bentuk lampau.',['We visits the museum yesterday.','We visiting the museum yesterday.','We visit the museum yesterday.']],
 ['Present perfect tense',['She','has already','finished','her project.'],'Present perfect: has + past participle finished. Already berada di antara has dan finished.',['She have already finished her project.','She has already finish her project.','She already finishing her project.']],
 ['Relative clauses',['The girl','who won the race','is','my neighbour.'],'Who won the race menjelaskan the girl; is menjadi kata kerja klausa utama.',['The girl which won the race is my neighbour.','The girl who won the race are my neighbour.','The girl who win the race were my neighbour.']],
 ['Simple future tense',['They','will','plant','a tree','tomorrow.'],'Sesudah will gunakan kata kerja dasar plant. Tomorrow menunjukkan masa depan.',['They will planted a tree tomorrow.','They will plants a tree tomorrow.','They planting a tree tomorrow.']],
 ['Conjunctions',['Although','it was raining,','we','continued','our walk.'],'Although memperkenalkan pertentangan: meskipun hujan, kegiatan berjalan tetap dilanjutkan.',['Although it was raining, we continues our walk.','Although it was rain, we continued our walk.','Although it was raining, we continuing our walk.']],
 ['Passive past tense',['The broken window','was','repaired','by the caretaker.'],'Subjek tunggal menerima tindakan lampau: was + repaired.',['The broken window were repaired by the caretaker.','The broken window was repair by the caretaker.','The broken window did repaired by the caretaker.']],
 ['Grammar',['My brother','usually reads','before bedtime.'],'Usually ditempatkan sebelum kata kerja utama reads; subjek tunggal memakai reads.',['My brother usually read before bedtime.','My brother usually reading before bedtime.','My brother usually are reads before bedtime.']],
 ['Tenses & advanced sentence structure',['While','I was reading,','the phone','rang.'],'Past continuous was reading menunjukkan kegiatan yang sedang berlangsung saat telepon berbunyi.',['While I was reading, the phone ring.','While I were reading, the phone rang.','While I reading, the phone rang.']],
 ['Tenses & advanced sentence structure',['If','we leave now,','we','will catch','the last bus.'],'First conditional: if + present simple, will + kata kerja dasar.',['If we leave now, we will caught the last bus.','If we leaves now, we will catch the last bus.','If we leave now, we would caught the last bus.']]
 ];
 orders.forEach(([tag,tokens,explanation,wrong],i)=>add('order',i+1,'grammar',tag,'Choose the correctly formed sentence.',[tokens.join(' '),...wrong],0,explanation,{tokens,instruction:'Susun potongan menjadi kalimat. Mulai dengan “'+tokens[0]+'” dan pertahankan tanda baca.'},'Target meaning: '+['Kami mengunjungi museum kemarin.','Dia sudah menyelesaikan proyeknya.','Gadis yang memenangkan lomba adalah tetanggaku.','Mereka akan menanam pohon besok.','Meskipun hujan, kami melanjutkan jalan-jalan.','Jendela yang pecah diperbaiki oleh penjaga.','Saudara laki-lakiku biasanya membaca sebelum tidur.','Saat aku sedang membaca, telepon berbunyi.','Jika kita berangkat sekarang, kita akan mendapat bus terakhir.'][i]));
 const evidence=[
 ['Content of the text',['Mina put a red notebook in her bag.','She left her blue pencil on the desk.','Then she walked to school.'],'What did Mina leave on the desk?',['A red notebook','A blue pencil','Her bag','Her shoes'],1,1,'Kalimat kedua secara langsung menyebut blue pencil ditinggalkan di meja.'],
 ['Reference',['The pupils collected fallen leaves.','They used the leaves to make a collage.','Their teacher displayed the artwork.'],'Who does “They” refer to?',['The teachers','The leaves','The pupils','The visitors'],2,0,'Kalimat pertama memperkenalkan para murid sebagai pelaku; They pada kalimat kedua merujuk kepada mereka.'],
 ['Inference & critical thinking',['Ravi checked both sides of the road.','He waited until the cars had passed before crossing.','His bag was green.'],'Which description is best supported?',['Ravi was careless','Ravi was cautious','Ravi disliked school','Ravi owned a car'],1,1,'Menunggu mobil lewat sebelum menyeberang mendukung sifat hati-hati. Warna tas tidak relevan.'],
 ['Purpose of the text',['Join our Saturday beach clean-up!','Meet at the north gate at nine.','Please bring gloves and a reusable bottle.'],'What is the writer’s main purpose?',['To invite people to help clean the beach','To sell a new bottle','To tell a fairy tale','To describe a mountain'],0,0,'Ajakan Join pada kalimat pembuka menunjukkan tujuan mengajak pembaca ikut membersihkan pantai.'],
 ['Finding main idea',['Our school library offers more than books.','Pupils can borrow board games and attend storytelling sessions.','There is also a quiet corner for studying.'],'Which is the best main idea?',['The library has many different uses','Board games are always expensive','Every pupil studies alone','Storytelling has been cancelled'],0,0,'Kalimat pembuka mencakup seluruh rincian: perpustakaan menyediakan lebih dari sekadar buku.'],
 ['Cause and effect',['The town installed more bins in the park.','Volunteers also began a weekly clean-up.','The park had less litter the next month.'],'Why can we not be certain that the bins alone caused the improvement?',['There was another change at the same time','The park had no paths','All bins disappeared','Litter cannot be collected'],0,1,'Pembersihan mingguan juga dimulai, sehingga pengaruh masing-masing perubahan belum dapat dipisahkan.'],
 ['Content of the text',['The nature club meets on Thursday.','The chess club meets on Monday.','Both clubs use Room 4.'],'On which day does the nature club meet?',['Monday','Tuesday','Thursday','Friday'],2,0,'Kalimat pertama menyebut jadwal nature club, yaitu Kamis.'],
 ['Reference',['Alya lent her umbrella to Jo.','This kept Jo dry on the way home.','Alya waited at the library.'],'What does “This” refer to?',['Waiting at the library','Lending the umbrella to Jo','The library building','Going to school'],1,0,'This merujuk pada tindakan meminjamkan payung dalam kalimat pertama.'],
 ['Inference & critical thinking',['Lea had practised her speech all week.','When her name was called, her hands trembled, but she walked onto the stage.','She wore a yellow shirt.'],'What can we reasonably infer?',['Lea felt nervous but chose to continue','Lea had never practised','Lea refused to speak','Lea was certainly the winner'],0,1,'Tangan gemetar menunjukkan gugup, tetapi berjalan ke panggung mendukung keberanian untuk tetap mencoba.']
 ];
 evidence.forEach(([tag,sentences,prompt,options,answer,proof,explanation],i)=>add('evidence',i+1,tag.includes('Inference')?'logic':'reading',tag,prompt,options,answer,explanation,{sentences,proof,...(i===2?{proofs:[0,1]}:{})},sentences.join(' ')));
 const edits=[
 ['Simple past tense',['She','go','to school','yesterday.'],1,['went','goes','going','gone'],0,'Yesterday membutuhkan bentuk lampau went, bukan go.'],
 ['Quantifier',['There are','much','apples','in the basket.'],1,['many','a little','any of','much of'],0,'Apples adalah kata benda yang dapat dihitung dan jamak, sehingga gunakan many.'],
 ['Subject–verb agreement',['Each of the players','have','a clean uniform.'],1,['has','are having yesterday','were have','having'],0,'Each menjadi inti subjek tunggal, jadi has. Players dalam frasa tambahan tidak mengubah kesesuaian kata kerja.'],
 ['Pronoun',['This bag','belongs to','I.'],2,['me.','my.','mine bag.','myself own.'],0,'Sesudah to diperlukan object pronoun me.'],
 ['Present perfect tense',['Rina','has','ate','her lunch.'],2,['eaten','eat','eating','eats'],0,'Has harus diikuti past participle; bentuk yang benar untuk eat adalah eaten.'],
 ['Relative clauses',['The boy','which','lives next door','is kind.'],1,['who','where','when','whose'],0,'Untuk orang yang menjadi subjek klausa relatif, gunakan who.'],
 ['Simple future tense',['Tomorrow,','we will','visited','the zoo.'],2,['visit','visits','visiting','visitor'],0,'Will diikuti kata kerja dasar visit.'],
 ['Passive past tense',['The invitations','was','sent','yesterday.'],1,['were','is','be','has'],0,'Invitations jamak sehingga past passive memakai were sent.'],
 ['Conjunctions',['We cannot enter','unless','we do not have','tickets.'],2,['we have','we has','we having','we had have'],0,'Makna yang dituju: tiket diperlukan untuk masuk. Unless sudah berarti if not, jadi gunakan unless we have tickets.']
 ];
 edits.forEach(([tag,chunks,bad,replacements,repair,explanation],i)=>{
  const fixed=chunks.map((c,j)=>j===bad?replacements[repair]:c).join(' '),options=replacements.map(r=>chunks.map((c,j)=>j===bad?r:c).join(' '));
  add('edit',i+1,'grammar',tag,'Which revision correctly repairs this sentence?',options,repair,explanation,{chunks,bad,replacements,repair,fixed},(i===8?'Intended meaning: A ticket is required to enter. Sentence: ':'')+chunks.join(' '));
 });
 function dialogue(n,title,root,explanation,nodes){
  add('dialogue',n,'social','Communication & social functions',root,nodes.start.choices.map(c=>c.text),nodes.start.choices.findIndex(c=>c.good),explanation,{title,nodes});
 }
 dialogue(1,'Misi perpustakaan','You want to borrow a book. What should you say first?','Mulailah dengan permintaan sopan, lalu berikan informasi yang diminta dan ucapkan terima kasih.',{
  start:{speaker:'Librarian',text:'Hello! How can I help you?',choices:[{text:'Could I borrow a book, please?',good:true,next:'card',reply:'Of course. Let me check your membership.'},{text:'Give me a book now!',good:false,next:'repair',reply:'I can help, but please ask politely.'},{text:'You are a book.',good:false,next:'repair',reply:'Do you want to borrow something?'},{text:'It is raining on Mars.',good:false,next:'repair',reply:'Let’s talk about what you need here.'}]},
  repair:{speaker:'Librarian',text:'How could you ask more politely?',choices:[{text:'Could I borrow a book, please?',good:true,next:'card',reply:'Certainly. Thank you for asking politely.'},{text:'Hurry up!',good:false,next:'card',reply:'A polite request would help. We still need your library card.'}]},
  card:{speaker:'Librarian',text:'May I see your library card?',choices:[{text:'Here you are. Thank you for your help.',good:true,next:null,reply:'You’re welcome! Your book is due next Friday.'},{text:'A card is a rectangle.',good:false,next:null,reply:'That describes a shape, but I need your membership card to lend you the book.'}]}
 });
 dialogue(2,'Teman setelah lomba','Your friend did not reach the final. Which reply is most supportive?','Akui perasaan teman, tawarkan bantuan tanpa memaksa, dan hormati kebutuhannya.',{
  start:{speaker:'Nia',text:'I practised a lot, but I did not reach the final.',choices:[{text:'That’s disappointing. Would you like to talk about it?',good:true,next:'listen',reply:'Yes. I got stuck on the last reading question.'},{text:'That is hilarious!',good:false,next:'repair',reply:'That hurts. I worked hard.'},{text:'You must never try again.',good:false,next:'repair',reply:'I still want to learn.'},{text:'My bag is blue.',good:false,next:'repair',reply:'I was hoping you would listen.'}]},
  repair:{speaker:'Nia',text:'I need a friend who will listen.',choices:[{text:'I’m sorry. Tell me what felt difficult.',good:true,next:'listen',reply:'Thank you. The last reading question was hard.'},{text:'Your feelings do not matter.',good:false,next:null,reply:'That is not supportive. Acknowledge a friend’s feelings before offering advice.'}]},
  listen:{speaker:'Nia',text:'I want to practise, but I’m tired right now.',choices:[{text:'Let’s take a break and practise together tomorrow.',good:true,next:null,reply:'That would help. Thank you for understanding.'},{text:'You must do fifty questions immediately.',good:false,next:null,reply:'I need rest first. Support should respect someone’s needs.'}]}
 });
 dialogue(3,'Rencana pameran','A teammate suggests an expensive display. How can you disagree respectfully?','Sampaikan kekhawatiran dengan sopan, jelaskan alasannya, lalu bantu mencari alternatif yang memenuhi kebutuhan kelompok.',{
  start:{speaker:'Ari',text:'Let’s buy a huge new display board for our project.',choices:[{text:'It could look good, but can we check our budget first?',good:true,next:'budget',reply:'Good point. We only have Rp50,000 left.'},{text:'That is the worst idea ever.',good:false,next:'repair',reply:'Could you explain your concern without insulting my idea?'},{text:'Yes, money can never run out.',good:false,next:'repair',reply:'We do have a limited budget.'},{text:'I refuse to discuss anything.',good:false,next:'repair',reply:'We need to make this decision together.'}]},
  repair:{speaker:'Ari',text:'What is your practical concern?',choices:[{text:'The board may cost more than we can afford.',good:true,next:'budget',reply:'Let’s compare the cost with our remaining Rp50,000.'},{text:'I just want to be in charge.',good:false,next:null,reply:'A shared decision needs reasons that relate to the project.'}]},
  budget:{speaker:'Ari',text:'The new board costs Rp80,000. We can reuse last year’s board for free.',choices:[{text:'Let’s reuse the old board and spend our money on labels.',good:true,next:null,reply:'That keeps us within budget and still makes the display clear.'},{text:'Let’s buy it without checking with anyone.',good:false,next:null,reply:'Rp80,000 exceeds our Rp50,000 budget. We need an affordable plan.'}]}
 });
 const words=[
 ['soil','tanah','Fill the pot with soil before planting the bean.','recipe'],['seed','biji','A seed can grow into a new plant.','recipe'],['forecast','prakiraan','The forecast says it may rain tomorrow.','weather'],['cloudy','berawan','The sky is cloudy, so we cannot see much sunshine.','weather'],['feather','bulu burung','An owl has soft feathers.','animals'],['wing','sayap','The butterfly has colourful wings.','animals'],['fur','bulu mamalia','The rabbit has thick fur.','animals'],['footprint','jejak kaki','A muddy footprint was left beside the door.','footprints'],['backpack','tas punggung','She carried her books in a backpack.','footprints'],['cousin','sepupu','My aunt’s daughter is my cousin.','family'],['niece','keponakan perempuan','My sister’s daughter is my niece.','family'],['nephew','keponakan laki-laki','My brother’s son is my nephew.','family'],
 ['polite','sopan','It is polite to say please when asking for help.','comic'],['grateful','berterima kasih','I felt grateful when Jo helped me carry my books.','comic'],['fragile','mudah pecah','The fragile cup broke when it fell.'],['tiny','sangat kecil','A tiny seed lay in the palm of my hand.','recipe'],['meticulous','sangat teliti','The meticulous editor checked every word twice.'],['ambiguous','bermakna ganda','The ambiguous instruction could be understood in two ways.'],['scarce','langka atau sulit didapat','Water was scarce during the long dry season.'],['reliable','dapat diandalkan','Our reliable neighbour always keeps her promises.'],['generous','murah hati','The generous pupil shared his lunch with a friend.'],['impartial','tidak memihak','An impartial judge treats both teams fairly.'],['resilient','mampu bangkit setelah kesulitan','The resilient team tried again after its first model collapsed.'],['evidence','bukti','The footprints were evidence that someone had walked through the mud.','footprints']
 ];
 words.forEach(([word,meaning,example,picture],i)=>{
  const id='lexicon-'+word,options=[meaning,...[1,7,13].map(offset=>words[(i+offset)%words.length][1])],answer=i%4;
  [options[0],options[answer]]=[options[answer],options[0]];
  QUEST_WORDS.push({id,word,meaning,example,picture});
  QUESTIONS.push({id,wordId:id,topic:'words',tag:'Advanced vocabulary',level:levels[Math.floor(i/8)],prompt:'What does “'+word+'” mean in this sentence?',options,answer,explanation:word+' berarti '+meaning+'. Perhatikan penggunaannya dalam contoh: '+example,passage:example});
 });
})();
