function createInteractiveQuest(api){
 const {$,esc}=api;let level='Explorer',search='',onlySaved=false,wordPage=0,cardId=null,revealed=false;
 const lex=()=>api.state.lexicon||(api.state.lexicon={saved:[],reviews:[],custom:[]});
 const words=()=>[...QUEST_WORDS,...lex().custom],word=id=>words().find(w=>w.id===id),saved=id=>lex().saved.some(w=>w.id===id);
 const current=()=>api.session?.questions[api.session.index];
 function getDraft(){const q=current();if(!Interactive.isActive(api.session))return null;let d=Interactive.draft(api.session.interactiveDraft,q);if(!d){d=Interactive.fresh(q);api.session.interactiveDraft=d;api.snapshot();}return d;}
 function controls(q,d){const t=Interactive.task(q),locked=api.session.answered,disabled=locked?'disabled':'';
  let body='';
  if(t.kind==='order')body=`<p>${esc(t.instruction)}</p><div class="sentence-tray" aria-label="Kalimat susunanmu">${d.order.length?d.order.map((i,n)=>`<button class="word-tile chosen" data-token-remove="${n}" ${disabled}>${esc(t.tokens[i])} ×</button>`).join(''):'<span>Ketuk potongan di bawah untuk mulai menyusun.</span>'}</div><div class="token-bank">${d.bankOrder.map(i=>`<button class="word-tile" data-token-add="${i}" ${d.order.includes(i)||locked?'disabled':''}>${esc(t.tokens[i])}</button>`).join('')}</div><button class="text-btn" id="order-clear" ${disabled}>Susun ulang</button>`;
  if(t.kind==='evidence')body=`<p><b>1.</b> Pilih jawaban.</p><div class="activity-options">${q.options.map((o,i)=>`<button class="secondary ${d.choice===i?'chosen':''}" aria-pressed="${d.choice===i}" data-evidence-answer="${i}" ${disabled}>${'ABCD'[i]}. ${esc(o)}</button>`).join('')}</div><p><b>2.</b> Ketuk kalimat yang paling langsung mendukung jawabanmu.</p><div class="evidence-lines">${t.sentences.map((s,i)=>`<button class="evidence-line ${d.proof===i?'chosen':''}" aria-pressed="${d.proof===i}" data-proof="${i}" ${disabled}><span>${i+1}</span>${esc(s)}</button>`).join('')}</div>`;
  if(t.kind==='edit')body=`<p><b>1.</b> Pilih bagian kalimat yang perlu diperbaiki.</p><div class="sentence-tray">${t.chunks.map((s,i)=>`<button class="word-tile ${d.part===i?'chosen':''}" aria-pressed="${d.part===i}" data-edit-part="${i}" ${disabled}>${esc(s)}</button>`).join('')}</div><p><b>2.</b> Pilih penggantinya.</p><div class="token-bank">${t.replacements.map((s,i)=>`<button class="word-tile ${d.replacement===i?'chosen':''}" aria-pressed="${d.replacement===i}" data-edit-replacement="${i}" ${disabled}>${esc(s)}</button>`).join('')}</div>${d.part!==null&&d.replacement!==null?`<p class="edit-preview"><b>Pratinjau:</b> ${esc(t.chunks.map((s,i)=>i===d.part?t.replacements[d.replacement]:s).join(' '))}</p>`:''}`;
  if(t.kind==='dialogue'){
   const node=Interactive.nodeFor(t,d.path);body=`<h3>${esc(t.title)}</h3><p class="notice">Pilihanmu menentukan balasan berikutnya. Jika kurang tepat, percakapan bisa memberi kesempatan memperbaiki respons.</p><div class="chat-log">${d.path.map(s=>{const n=t.nodes[s.node],c=n.choices[s.choice];return `<p class="chat other"><b>${esc(n.speaker)}:</b> ${esc(n.text)}</p><p class="chat mine"><b>Kamu:</b> ${esc(c.text)}</p><p class="chat reply">${esc(c.reply)}</p>`;}).join('')}</div>${node?`<p class="chat other"><b>${esc(t.nodes[node].speaker)}:</b> ${esc(t.nodes[node].text)}</p><div class="activity-options">${t.nodes[node].choices.map((c,i)=>`<button class="secondary" data-dialogue-choice="${i}" ${disabled}>${esc(c.text)}</button>`).join('')}</div>`:'<p class="notice">Percakapan selesai. Simpan hasil untuk melihat pembahasannya.</p>'}`;
  }
  return `<div class="activity-controls">${body}<p id="activity-error" role="status"></p><button class="primary" id="activity-submit" ${disabled}>${t.kind==='dialogue'?'Selesaikan percakapan':'Periksa jawabanku'} →</button></div>`;
 }
 function question(q){if(!Interactive.isActive(api.session))return '';return `<section class="interaction-zone" tabindex="-1" aria-label="Aktivitas interaktif">${controls(q,getDraft())}</section>`;}
 function refresh(){const holder=$('.interaction-zone');if(holder){holder.innerHTML=controls(current(),getDraft());holder.focus({preventScroll:true});}}
 function update(fn){if(!Interactive.isActive(api.session)||api.session.answered)return;const d=getDraft();fn(d);api.session.interactiveDraft=d;api.snapshot();refresh();}
 function feedback(q,a){const result=Interactive.evaluate(q,a.interaction?.draft);return `<b>${a.correct?'✨ Tepat sekali! +20 XP':'🌱 Terus berlatih. +5 XP'}</b><p>${esc(result.detail)}</p><p>${esc(q.explanation)}</p>`;}
 function result(q,a){return a.interaction?`<b>Jawabanmu:</b> ${esc(Interactive.evaluate(q,a.interaction.draft).response)}<br>${esc(Interactive.evaluate(q,a.interaction.draft).detail)}<br>${esc(q.explanation)}`:'';}
 function lock(){document.querySelectorAll('.activity-controls button').forEach(b=>b.disabled=true);}
 function card(){return `<section class="panel workshop-invite"><span class="eyebrow">TRY · EXPLAIN · CREATE</span><h2>Belajar dengan cara baru 🧩</h2><p>Susun kalimat, cari bukti, jadi editor, dan jalani percakapanmu sendiri.</p><div class="milestone-actions"><button class="primary" data-start="play:daily:Explorer">Daily interaktif · 5 tantangan →</button><button class="secondary" data-page="workshop">Pilih aktivitas</button><button class="text-btn" data-page="dictionary">📚 Kamus Petualang</button></div></section>`;}
 function hub(){const modes=[['order','🧩','Susun Kalimat','Ketuk potongan kata untuk membangun kalimat yang tepat.'],['evidence','🔎','Cari Bukti','Pilih jawaban dan kalimat pendukungnya.'],['edit','🛠️','Bengkel Kalimat','Temukan kesalahan lalu pilih perbaikannya.'],['dialogue','🎭','Percakapan Bercabang','Pilihanmu mengubah jalannya percakapan.']];return `<h1>Studio petualang bahasa ✨</h1><p class="sub">Empat cara aktif memahami bahasa Inggris. Nilai, XP, dan Sesi Siswa tersambung dengan progresmu.</p><div class="filters"><label for="workshop-level">Tingkat aktivitas</label><select id="workshop-level">${['Explorer','Challenger','Champion','all'].map(l=>`<option value="${l}" ${level===l?'selected':''}>${l==='all'?'Campuran':l}</option>`).join('')}</select><button class="primary" data-start="play:daily:${level}">Daily interaktif · 5 tantangan</button></div><p class="notice">Daily Campuran dimulai dari Explorer. Setiap tantangan lengkap mendapat 20 XP jika tepat, 5 XP jika belum tepat. Cari Bukti membutuhkan jawaban dan bukti yang tepat; percakapan menilai seluruh respons pertama yang dipilih. Ujian tetap memakai pilihan ganda.</p><div class="workshop-grid">${modes.map(([id,icon,name,desc])=>{const count=Math.min(id==='dialogue'?1:5,QUESTIONS.filter(q=>q.activity===id&&(level==='all'||q.level===level)).length);return `<section class="panel workshop-mode"><span class="big-icon">${icon}</span><h2>${name}</h2><p>${desc}</p><button class="secondary" data-start="play:${id}:${level}">Mulai · ${count} ${id==='dialogue'?'percakapan':'tantangan'} →</button></section>`;}).join('')}</div><section class="panel workshop-invite"><h2>📚 Kamus Petualang pribadi</h2><p>Simpan kata dari koleksi, atau tambahkan kata, arti, dan contoh buatanmu. Latih kembali dengan kuis dan kartu ingatan.</p><button class="primary" data-page="dictionary">Buka kamus · ${lex().saved.length} kata tersimpan →</button></section>${progress()}`;}
 function progress(){const all=api.state.attempts.filter(a=>a.interaction),proof=all.filter(a=>Interactive.task(QUESTIONS.find(q=>q.id===a.id))?.kind==='evidence');return `<section class="panel workshop-progress"><h2>Jejak aktivitas interaktif</h2><div class="workshop-metrics">${[['Tantangan selesai',all.length],['Tepat',all.filter(a=>a.correct).length],['Kata tersimpan',lex().saved.length],['Kata siap diulang',lex().saved.filter(s=>Interactive.wordStatus(api.state,s.id,api.dateKey()).dueNow).length]].map(([k,v])=>`<div><strong>${v}</strong><span>${k}</span></div>`).join('')}</div>${proof.length?`<p>Cari Bukti: ${proof.filter(a=>a.selected===QUESTIONS.find(q=>q.id===a.id).answer).length}/${proof.length} jawaban tepat; ${proof.filter(a=>{const t=ACTIVE_TASKS[a.id];return (t.proofs||[t.proof]).includes(a.interaction.draft.proof);}).length}/${proof.length} bukti tepat. Nilai tantangan benar jika keduanya tepat.</p>`:''}<p class="notice">Latihan interaktif masuk grafik harian, XP, dan hitungan hari belajar. Kartu ingatan adalah penilaian diri; tidak menambah XP atau nilai ujian.</p></section>`;}
 function changeLex(fn){const before=JSON.parse(JSON.stringify(lex()));fn(lex());if(!api.save()){api.state.lexicon=before;return false;}return true;}
 function list(){const pool=onlySaved?words():Weekly.dailyWords(QUEST_WORDS,api.dateKey());const matches=pool.filter(w=>(!onlySaved||saved(w.id))&&[w.word,w.meaning,w.example].join(' ').toLowerCase().includes(search.toLowerCase()));wordPage=Math.min(wordPage,Math.max(0,Math.ceil(matches.length/6)-1));const shown=matches.slice(wordPage*6,wordPage*6+6);return shown.length?shown.map(w=>`<article class="panel word-card"><div class="title-row"><h2>${esc(w.word)}</h2><span class="tag">${w.id.startsWith('personal-')?'Catatanmu':'Koleksi'}</span></div><p><b>${esc(w.meaning)}</b></p><p class="word-example">${esc(w.example||'Tambahkan konteks saat mengingat kata ini.')}</p>${w.picture?`<details><summary>Ilustrasi konteks</summary>${PictureQuest.visual({picture:w.picture})}</details>`:'<span class="word-symbol" aria-hidden="true">📖</span>'}<div class="milestone-actions"><button class="secondary" data-save-word="${w.id}">${saved(w.id)?'✓ Tersimpan · Lepas':'＋ Simpan kata'}</button>${saved(w.id)?`<button class="text-btn" data-flash-word="${w.id}">Kartu ingatan →</button>`:''}</div>${saved(w.id)?`<p class="notice">${Interactive.wordStatus(api.state,w.id,api.dateKey()).dueNow?'Siap diulang':'Ulangi pada '+Interactive.wordStatus(api.state,w.id,api.dateKey()).due}</p>`:''}</article>`).join('')+`<div class="word-pagination"><button class="secondary" data-word-page="-1" ${wordPage===0?'disabled':''}>← Sebelumnya</button><span>Halaman ${wordPage+1} / ${Math.ceil(matches.length/6)}</span><button class="secondary" data-word-page="1" ${(wordPage+1)*6>=matches.length?'disabled':''}>Berikutnya →</button></div>`:'<p class="empty">Belum ada kata yang cocok. Kamu bisa menambahkannya melalui formulir di bawah.</p>';}
 function flash(){const w=word(cardId);if(!w||!saved(w.id))return '';return `<section class="panel flash-card"><span class="eyebrow">KARTU INGATAN · PENILAIAN DIRI</span><h2>${esc(w.word)}</h2>${revealed?`<p><b>${esc(w.meaning)}</b></p><p>${esc(w.example)}</p><div class="milestone-actions"><button class="secondary" data-flash-grade="no">Masih belajar</button><button class="primary" data-flash-grade="yes">Sudah ingat</button></div>`:'<p>Coba ingat arti dan buat satu contoh sebelum membuka kartu.</p><button class="primary" id="flash-reveal">Lihat arti →</button>'}</section>`;}
 function dictionary(){return `<h1>Kamus Petualang 📚</h1><p class="daily-word-note">6 kata hari ini · ${api.dateKey()}. Berganti otomatis setiap tanggal lokal. Setelah koleksi habis, kata diulang untuk memperkuat ingatan.</p><p class="sub">${lex().saved.length} kata tersimpan · ${QUEST_WORDS.length} kata dalam koleksi · ${lex().custom.length} catatan buatanmu.</p><section class="panel dictionary-coach"><h2>Ingat kembali, sedikit demi sedikit</h2><p>Kata dari koleksi dapat dilatih lewat kuis. Semua kata, termasuk catatanmu, tersedia dalam kartu ingatan. Pengulangan dijadwalkan bertahap pada hari berbeda.</p><div class="milestone-actions"><button class="primary" data-start="play:words">Kuis kata tersimpan · hingga 5 soal</button><button class="secondary" id="flash-start" ${lex().saved.length?'':'disabled'}>Mulai kartu ingatan</button></div></section><div id="flash-area">${flash()}</div><div class="filters"><input id="word-search" value="${esc(search)}" placeholder="Cari kata atau arti…" aria-label="Cari kata"><select id="word-filter" aria-label="Filter kamus"><option value="all" ${onlySaved?'':'selected'}>6 kata hari ini</option><option value="saved" ${onlySaved?'selected':''}>Kata tersimpan</option></select></div><div class="lexicon-list">${list()}</div><section class="panel custom-word"><h2>Tambahkan kata penemuanmu</h2><p class="notice">Catatan pribadi ditampilkan apa adanya. Periksa arti dengan guru atau sumber belajarmu. Maksimal 200 catatan.</p><label for="custom-word">Kata bahasa Inggris</label><input id="custom-word" maxlength="50" placeholder="Contoh: curious"><label for="custom-meaning">Arti</label><input id="custom-meaning" maxlength="150" placeholder="Contoh: ingin tahu"><label for="custom-example">Contoh kalimat (opsional)</label><textarea id="custom-example" maxlength="300" placeholder="She is curious about how plants grow."></textarea><label for="custom-picture">Ilustrasi konteks (opsional)</label><select id="custom-picture"><option value="">Tanpa ilustrasi</option>${Object.entries(PictureQuest.scenes).map(([key,s])=>`<option value="${key}">${esc(s.title)}</option>`).join('')}</select><p id="word-error" role="status"></p><button class="primary" id="add-custom-word">Simpan ke kamus</button></section>`;}
 function related(q){const content=[q.prompt,q.passage,...q.options].join(' ').toLowerCase();return QUEST_WORDS.filter(w=>new RegExp('\\b'+w.word+'(?:s|es)?\\b','i').test(content)).slice(0,5);}
 function extras(q){if(api.session?.exam)return '';const found=related(q);return found.length?`<section class="word-tools"><b>📚 Kata untuk kamusmu</b><p class="notice">Membuka arti sebelum menjawab dicatat sebagai bantuan.</p>${found.map(w=>`<div class="word-tool"><span>${esc(w.word)}</span><button class="text-btn" data-save-word="${w.id}">${saved(w.id)?'✓ Tersimpan':'＋ Simpan'}</button><button class="text-btn" data-word-meaning="${w.id}">Lihat arti</button></div>`).join('')}<div id="word-meaning" aria-live="polite"></div></section>`:'';}
 function record(q,a){if(q.wordId&&saved(q.wordId)){lex().reviews.push({id:q.wordId,date:a.date,correct:a.correct,assisted:a.assisted,type:'quiz'});lex().reviews=lex().reviews.slice(-10000);}}
 function click(b){
  const ds=b.dataset;
  if(ds.wordPage){wordPage+=Number(ds.wordPage);$('.lexicon-list').innerHTML=list();return true;}
  if(ds.tokenAdd!==undefined){update(d=>{const n=Number(ds.tokenAdd);if(!d.order.includes(n))d.order.push(n);});return true;}
  if(ds.tokenRemove!==undefined){update(d=>d.order.splice(Number(ds.tokenRemove),1));return true;}
  if(b.id==='order-clear'){update(d=>d.order=[]);return true;}
  for(const [key,field] of [['evidenceAnswer','choice'],['proof','proof'],['editPart','part'],['editReplacement','replacement']])if(ds[key]!==undefined){update(d=>d[field]=Number(ds[key]));return true;}
  if(ds.dialogueChoice!==undefined){update(d=>{const t=Interactive.task(current()),node=Interactive.nodeFor(t,d.path),choice=Number(ds.dialogueChoice);if(node&&t.nodes[node].choices[choice])d.path.push({node,choice});});document.querySelectorAll('[data-confidence]').forEach(button=>button.disabled=true);return true;}
  if(b.id==='activity-submit'){if(!Interactive.isActive(api.session)||api.session.answered)return true;const d=getDraft(),r=Interactive.evaluate(current(),d);if(!r.complete){$('#activity-error').textContent='Lengkapi semua langkah dahulu: susun semua potongan, pilih jawaban dan bukti, atau selesaikan percakapannya.';return true;}api.answer(r.selected,{draft:d});return true;}
  if(ds.saveWord){const w=word(ds.saveWord);if(!w)return true;const was=saved(w.id);if(changeLex(l=>{l.saved=was?l.saved.filter(s=>s.id!==w.id):[...l.saved,{id:w.id,date:api.dateKey()}];})){if(api.page==='dictionary')api.navigate('dictionary');else{document.querySelectorAll('[data-save-word]').forEach(button=>{if(button.dataset.saveWord===w.id)button.textContent=was?'＋ Simpan':'✓ Tersimpan';});api.toast(was?'Kata dilepas dari daftar tersimpan.':'Kata tersimpan dalam Kamus Petualang.');}}return true;}
  if(ds.wordMeaning){const w=word(ds.wordMeaning);if(!w||api.session?.exam)return true;const s=api.session;if(s&&!s.answered){s.helped=s.helped||[];if(!s.helped.includes(current().id))s.helped.push(current().id);api.snapshot();}$('#word-meaning').innerHTML=`<p><b>${esc(w.word)}:</b> ${esc(w.meaning)}<br>${esc(w.example)}</p>`;return true;}
  if(b.id==='add-custom-word'){const entry={id:'personal-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),word:$('#custom-word').value.trim(),meaning:$('#custom-meaning').value.trim(),example:$('#custom-example').value.trim(),picture:$('#custom-picture').value||undefined};if(!entry.word||!entry.meaning){$('#word-error').textContent='Isi kata dan artinya dahulu.';return true;}if(lex().custom.length>=200){$('#word-error').textContent='Batas 200 catatan pribadi sudah tercapai.';return true;}if(words().some(w=>w.word.toLowerCase()===entry.word.toLowerCase())){$('#word-error').textContent='Kata ini sudah ada. Cari dan simpan melalui daftar kata.';return true;}if(entry.word.length>50||entry.meaning.length>150||entry.example.length>300){$('#word-error').textContent='Catatan terlalu panjang.';return true;}if(changeLex(l=>{l.custom.push(entry);l.saved.push({id:entry.id,date:api.dateKey()});})){search=entry.word;onlySaved=true;api.navigate('dictionary');}return true;}
  if(b.id==='flash-start'||ds.flashWord){cardId=ds.flashWord||[...lex().saved].sort((a,b)=>Interactive.wordStatus(api.state,a.id,api.dateKey()).due.localeCompare(Interactive.wordStatus(api.state,b.id,api.dateKey()).due))[0]?.id;revealed=false;$('#flash-area').innerHTML=flash();$('#flash-area').scrollIntoView?.({behavior:'smooth',block:'center'});return true;}
  if(b.id==='flash-reveal'){revealed=true;$('#flash-area').innerHTML=flash();return true;}
  if(ds.flashGrade){if(!cardId||!revealed||!saved(cardId))return true;const id=cardId;if(changeLex(l=>{l.reviews.push({id,date:api.dateKey(),correct:ds.flashGrade==='yes',assisted:false,type:'self'});l.reviews=l.reviews.slice(-10000);})){cardId=null;revealed=false;api.navigate('dictionary');api.toast('Catatan ingatan tersimpan. Pengulangan di hari yang sama tidak menaikkan tahap.');}return true;}
  return false;
 }
 function input(e){if(e.target.id==='word-search'){search=e.target.value;wordPage=0;$('.lexicon-list').innerHTML=list();return true;}return false;}
 function change(e){if(e.target.id==='workshop-level'){level=['all',...EQ.levels].includes(e.target.value)?e.target.value:'Explorer';api.navigate('workshop');return true;}if(e.target.id==='word-filter'){onlySaved=e.target.value==='saved';wordPage=0;$('.lexicon-list').innerHTML=list();return true;}return false;}
 return {question,feedback,result,lock,card,hub,progress,dictionary,extras,record,click,input,change,reset(){level='Explorer';search='';onlySaved=false;wordPage=0;cardId=null;revealed=false;}};
}
