// Specific distractor explanations; other questions reuse their grounded concept explanation.
for(const [id,notes] of Object.entries({
  'words-1':['Careless berarti ceroboh, bertentangan dengan kebiasaan mengecek dua kali.','Very careful sesuai dengan petunjuk mengecek setiap pengukuran dua kali.','Impatient berarti tidak sabar; teks memberi petunjuk ketelitian, bukan ketidaksabaran.','Very quick berarti sangat cepat; mengecek dua kali tidak membuktikan kecepatan.'],
  'words-3':['Nest adalah tempat telur diletakkan, bukan hasil pertumbuhan telur.','Telur berkembang menjadi burung, seperti biji berkembang menjadi tanaman.','Feather adalah bagian tubuh burung, bukan hewan yang berkembang dari telur.','Tree berkembang dari biji, bukan dari telur.'],
  'grammar-1':['Find adalah bentuk dasar. Dalam kalimat positif dengan yesterday, diperlukan bentuk lampau.','Finds dipakai untuk present simple dengan subjek tunggal, bukan kejadian kemarin.','Found adalah bentuk lampau tidak beraturan dari find, sesuai yesterday.','Finding tidak dapat menjadi kata kerja utama kalimat ini tanpa kata bantu yang sesuai.'],
  'grammar-4':['Honest diawali bunyi vokal, jadi a honest tidak tepat. University justru diawali bunyi /y/.','An honest dan a university tepat karena artikel mengikuti bunyi pertama.','An honest sudah tepat, tetapi university membutuhkan a, bukan an.','A university sudah tepat, tetapi honest membutuhkan an karena h tidak dibaca.'],
  'grammar-7':['Will stay melengkapi pola if + present simple, will + kata kerja dasar untuk kemungkinan besok.','Stayed menyatakan masa lampau, padahal konteksnya kemungkinan besok.','Would stayed tidak mengikuti pola modal + kata kerja dasar dan tidak cocok dengan first conditional ini.','Staying sendiri tidak dapat menjadi predikat lengkap setelah we di sini.'],
  'reading-1':['Teks tidak berfokus pada harga sayuran; yang dibahas ialah kebun dan manfaat belajarnya.','Pilihan ini merangkum dua bagian teks: hasil makanan dan kesempatan belajar.','Matematika hanya salah satu contoh. Pilihan ini terlalu sempit untuk keseluruhan teks.','Murid justru menggunakan air hujan untuk berkebun; teks tidak mengatakan air hujan tidak cocok.'],
  'reading-4':['Teks secara langsung menyebut pupils mixed in compost untuk memperbaiki tanah.','Tanaman tetap ditanam dengan membandingkan tempat cerah dan teduh; tidak ada tindakan menghilangkan semua cahaya.','Mengukur bedeng disebut dalam pelajaran matematika, tetapi mengecatnya tidak disebut.','Teks menyebut rainwater, bukan seawater. Jangan mengganti informasi sumber air.'],
  'social-1':['Good night lazim dipakai saat berpisah pada malam hari atau akan tidur, bukan saat menyapa pukul 8 pagi.','Good morning sesuai dengan waktu pagi dan sapaan sopan kepada guru.','Goodbye forever adalah perpisahan permanen, tidak sesuai pertemuan pagi hari.','Sweet dreams adalah ucapan menjelang tidur, bukan sapaan di sekolah pada pagi hari.'],
  'social-5':['Menertawakan kegagalan teman tidak menunjukkan dukungan.','Menyuruh teman tidak mencoba lagi menutup kesempatan memperbaiki diri.','Ucapan ini menunjukkan empati dan menawarkan latihan bersama.','Membicarakan kemenangan sendiri mengabaikan perasaan teman yang sedang kecewa.'],
  'logic-1':['Payung basah tidak membuktikan salju, terlebih lagi tidak membuktikannya secara pasti.','Payung basah dan sepatu berlumpur mendukung kemungkinan hujan. Kata may menjaga kesimpulan tetap proporsional.','Tidak ada informasi tentang apakah Raka menyukai sekolah.','Kondisi basah tidak menunjukkan usia payung; baru atau lama tidak dapat disimpulkan.'],
  'logic-2':['Aturan mengatakan semua anggota memakai lencana biru, bukan bahwa setiap pemakai lencana biru pasti anggota.','Mira termasuk anggota science club, sehingga aturan lencana biru berlaku padanya.','Keanggotaan tidak memberi bukti bahwa Mira memimpin klub.','Semua anggota memakai lencana biru; tidak ada dasar bahwa hanya Mira yang memilikinya.'],
  'stories-1':['Fox terburu-buru dan kehilangan buahnya, jadi cerita tidak mendukung klaim bahwa tergesa-gesa selalu menghemat waktu.','Tortoise berhasil membawa semua buah dengan upaya yang hati-hati dan bertahap.','Tortoise yang kecil justru berhasil bekerja dengan tekun.','Buah jatuh ke sungai, tetapi itu tidak berarti buah tumbuh di sungai.']
})){const question=QUESTIONS.find(q=>q.id===id);if(question)question.optionNotes=notes;}
