// Tambahkan topik ke TOPICS dan soal dengan q(). Jawaban benar adalah indeks 0–3.
const TOPICS = [
{id:'words',name:'Word Forest',icon:'🌿',color:'#eaf1de',desc:'Temukan makna, hubungan kata, dan ungkapan baru.',tags:['Advanced vocabulary','Word relationship & thematic expressions','General knowledge']},
{id:'grammar',name:'Grammar Galaxy',icon:'🪐',color:'#eee8f7',desc:'Jelajahi pola kalimat dan taklukkan tantangan grammar.',tags:['Grammar','Tenses & advanced sentence structure','Simple past tense','Simple future tense','Determiner','Quantifier','Pronoun']},
{id:'reading',name:'Reading Island',icon:'🏝️',color:'#e3eff4',desc:'Baca, cari petunjuk, dan ungkap pesan di balik teks.',tags:['Reference','Informational & longer texts','Paragraph','Finding main idea','Purpose of the text','Content of the text','Incomplete text']},
{id:'social',name:'Conversation Town',icon:'💬',color:'#f9edd9',desc:'Gunakan bahasa Inggris dalam situasi sehari-hari.',tags:['Everyday English','Communication & social functions','Greeting','Family tree','Gratitude']},
{id:'logic',name:'Detective Academy',icon:'🔎',color:'#f5e5e1',desc:'Hubungkan petunjuk dengan logika dan kesimpulan tepat.',tags:['Language reasoning','Inference & critical thinking']},
{id:'stories',name:'Story Castle',icon:'🏰',color:'#e6edfa',desc:'Masuki dunia cerita, pengalaman, dan tokoh inspiratif.',tags:['Narrative text','Recount text','Biography','Descriptive text']}
];
const QUESTIONS=[];
function q(topic,tag,level,prompt,options,answer,explanation,passage=''){QUESTIONS.push({id:topic+'-'+(QUESTIONS.filter(x=>x.topic===topic).length+1),topic,tag,level,prompt,options,answer,explanation,passage});}
q('words','Advanced vocabulary','Challenger','The scientist was meticulous: she checked every measurement twice. “Meticulous” means …',['careless','very careful','impatient','very quick'],1,'Petunjuk “checked every measurement twice” menunjukkan ketelitian. Meticulous berarti sangat teliti.');
q('words','Advanced vocabulary','Explorer','Which word is the opposite of “scarce”?',['rare','limited','abundant','missing'],2,'Scarce berarti langka atau sedikit; abundant berarti berlimpah.');
q('words','Word relationship & thematic expressions','Challenger','Seed is to plant as egg is to …',['nest','bird','feather','tree'],1,'Hubungannya adalah asal perkembangan: biji menjadi tanaman, telur berkembang menjadi burung.');
q('words','Word relationship & thematic expressions','Champion','“Let’s break the ice before the meeting.” What does the speaker suggest?',['Make the room colder','Cancel the meeting','Start a friendly conversation','Drink some water'],2,'Break the ice adalah idiom untuk mencairkan suasana, biasanya dengan percakapan ramah.');
q('words','Advanced vocabulary','Challenger','A resilient person usually …',['gives up immediately','recovers after difficulties','avoids all challenges','never feels sad'],1,'Resilient berarti mampu bangkit setelah kesulitan, bukan berarti tidak pernah sedih.');
q('words','General knowledge','Explorer','Which source of energy is renewable?',['Coal','Petroleum','Sunlight','Natural gas'],2,'Energi matahari dapat terus diperbarui secara alami; tiga pilihan lain adalah bahan bakar fosil.');
q('words','Word relationship & thematic expressions','Challenger','Which word does NOT belong in the group?',['generous','kind','helpful','selfish'],3,'Generous, kind, dan helpful menggambarkan kepedulian. Selfish berarti mementingkan diri sendiri.');
q('words','Advanced vocabulary','Champion','The instructions were ambiguous, so the teams built different models. The instructions were …',['open to more than one interpretation','easy to follow exactly','extremely detailed','written in two colours'],0,'Ambiguous berarti memiliki lebih dari satu kemungkinan makna. Model yang berbeda menjadi petunjuknya.');
q('words','General knowledge','Challenger','A caterpillar changes into a butterfly. This process is called …',['evaporation','metamorphosis','erosion','condensation'],1,'Metamorphosis adalah perubahan bentuk tubuh dalam siklus hidup hewan.');
q('words','Word relationship & thematic expressions','Explorer','Which phrase naturally completes “Please ___ attention”?',['do','make','pay','take'],2,'Kolokasi yang tepat adalah pay attention, artinya memperhatikan.');
q('grammar','Simple past tense','Explorer','Yesterday, Maya ___ her lost notebook under the desk.',['find','finds','found','finding'],2,'Yesterday menandai masa lampau. Bentuk past dari find adalah found.');
q('grammar','Simple past tense','Challenger','Which sentence is correct?',['Did you went to the museum?','Did you go to the museum?','Did you goes to the museum?','Do you went to the museum?'],1,'Sesudah did, gunakan kata kerja dasar: go, bukan went.');
q('grammar','Simple future tense','Explorer','I think our team ___ the match tomorrow.',['won','wins yesterday','will win','winning'],2,'Prediksi masa depan dapat menggunakan will + kata kerja dasar.');
q('grammar','Determiner','Challenger','Nina is ___ honest student who studies at ___ university.',['a / an','an / a','an / an','a / a'],1,'Honest dimulai bunyi vokal karena h tidak dibaca. University dimulai bunyi /y/, sehingga memakai a.');
q('grammar','Quantifier','Challenger','We have ___ time, so we can check our answers once more.',['a little','few','many','a few'],0,'Time tidak dapat dihitung di sini. A little berarti ada sedikit waktu yang masih bisa digunakan.');
q('grammar','Pronoun','Explorer','This pencil belongs to Amir. It is ___.',['him','he','his','himself'],2,'His dapat menjadi possessive pronoun, menggantikan “his pencil”.');
q('grammar','Tenses & advanced sentence structure','Champion','If it rains tomorrow, we ___ indoors.',['will stay','stayed','would stayed','staying'],0,'First conditional: if + present simple, will + kata kerja dasar.');
q('grammar','Tenses & advanced sentence structure','Champion','By the time we arrived, the film ___.',['has begun','had begun','will begin','begins'],1,'Past perfect (had begun) menunjukkan kejadian yang sudah berlangsung sebelum kejadian lampau lain.');
q('grammar','Grammar','Challenger','Each of the students ___ a library card.',['have','has','are having yesterday','were'],1,'Each adalah subjek tunggal, jadi menggunakan has.');
q('grammar','Quantifier','Champion','There are ___ chairs for everyone; nobody needs to stand.',['enough','little','much','any'],0,'Enough berarti cukup. Klausa “nobody needs to stand” menunjukkan kursinya mencukupi.');
q('grammar','Determiner','Explorer','___ books on the shelf over there belong to my sister.',['This','That','Those','An'],2,'Those menunjuk benda jamak yang jauh. Books adalah jamak.');
q('grammar','Pronoun','Challenger','Sita and I made the model by ___.',['themselves','ourselves','herself','yourselves'],1,'Sita and I sama dengan we. Reflexive pronoun untuk we adalah ourselves.');
const garden='At River School, pupils turned an unused corner into a vegetable garden. At first, the soil was dry and hard. The pupils mixed in compost and collected rainwater in barrels. After six weeks, they harvested spinach and beans. Some vegetables went to the school kitchen, while the rest were shared with neighbours.\n\nThe garden also changed lessons. In mathematics, pupils measured the beds. In science, they compared plant growth in sunny and shady spots. Their teacher said the most valuable harvest was not the vegetables, but the pupils’ growing ability to solve problems together.';
q('reading','Finding main idea','Challenger','What is the main idea of the text?',['Vegetables are expensive to buy','A school garden provides food and learning opportunities','Maths is easier outdoors','Rainwater is unsuitable for gardens'],1,'Kedua paragraf membahas manfaat kebun: hasil makanan dan kesempatan belajar bersama.',garden);
q('reading','Reference','Challenger','In “they harvested spinach and beans”, “they” refers to …',['the neighbours','the barrels','the pupils','the vegetables'],2,'Pelaku yang mengolah kebun dan memanen adalah para murid.',garden);
q('reading','Purpose of the text','Challenger','Why did the writer write this text?',['To explain the benefits of a school project','To sell gardening equipment','To warn children against vegetables','To describe a cooking competition'],0,'Teks memaparkan proyek kebun dan hasilnya, tanpa ajakan membeli atau peringatan.',garden);
q('reading','Content of the text','Explorer','What did pupils do to improve the soil?',['Added compost','Removed all sunlight','Painted the beds','Used seawater'],0,'Informasi dinyatakan langsung: “The pupils mixed in compost”.',garden);
q('reading','Informational & longer texts','Champion','What does “the most valuable harvest” suggest?',['The beans cost the most money','The teamwork mattered more than the vegetables','The garden failed to produce food','Only science lessons improved'],1,'Harvest digunakan secara kiasan untuk hasil belajar berupa kemampuan memecahkan masalah bersama.',garden);
q('reading','Paragraph','Challenger','Which sentence best starts a paragraph about saving water?',['My shoes are blue','There are several simple ways to use less water at home','The tallest mountain is far away','Yesterday I bought a novel'],1,'Kalimat pembuka harus memperkenalkan gagasan utama paragraf, yaitu cara menghemat air.');
q('reading','Incomplete text','Challenger','Choose the best connector: “The path was muddy. ___, the hikers continued carefully.”',['Therefore','However','For example','Because'],1,'However menunjukkan pertentangan: jalannya berlumpur, tetapi mereka tetap melanjutkan perjalanan.');
q('reading','Incomplete text','Champion','Choose the best sentence for the gap.',['They decided to sort the waste into separate bins','They stopped reading all books','The river was the longest in the world','Everyone forgot the project immediately'],0,'Kalimat yang tepat menghubungkan masalah sampah tercampur dengan hasil berupa daur ulang yang lebih mudah.','The class noticed that paper and food scraps were being thrown into the same bin. ___. Within a month, much more paper could be recycled.');
q('reading','Reference','Champion','What does “this” refer to?',['The library building','The action of lending books to younger children','The younger children’s age','A broken bicycle'],1,'This merujuk pada tindakan dalam kalimat sebelumnya, bukan hanya satu benda.','Every Friday, Ana lends her books to younger children. This has helped them develop a love of reading.');
q('reading','Informational & longer texts','Challenger','Which statement is supported by the text?',['All seeds travel by wind','Hooks help some seeds attach to animals','Animals deliberately plant every seed','Heavy seeds always float'],1,'Teks menyatakan biji berkait dapat menempel pada bulu hewan. Pilihan lain membuat klaim yang tidak didukung.','Plants spread their seeds in different ways. Light seeds may be carried by the wind. Some seeds have hooks that catch on animal fur. Others are inside fruits that animals eat. These methods help young plants grow away from the parent plant.');
q('social','Greeting','Explorer','It is 8 a.m. You meet your teacher. What is most appropriate?',['Good night, Mrs Lee','Good morning, Mrs Lee','Goodbye forever','Sweet dreams'],1,'Pukul 8 pagi menggunakan good morning. Good night biasanya saat berpisah malam atau akan tidur.');
q('social','Gratitude','Explorer','“Thank you for helping me carry these books.” Choose the best reply.',['You’re welcome','I am sorry for your loss','How old are you?','Never speak again'],0,'You’re welcome adalah respons sopan terhadap ucapan terima kasih.');
q('social','Family tree','Challenger','Lina is my mother’s sister. Lina’s son is my …',['uncle','nephew','cousin','grandfather'],2,'Anak dari saudara ayah atau ibu adalah cousin (sepupu).');
q('social','Family tree','Champion','Arif and Beni are brothers. Citra is Arif’s daughter. What is Beni to Citra?',['Her cousin','Her uncle','Her nephew','Her grandfather'],1,'Beni adalah saudara ayah Citra, sehingga ia adalah paman (uncle) Citra.');
q('social','Communication & social functions','Challenger','Your friend says, “I didn’t pass the selection.” What is the most supportive reply?',['That’s funny','You should never try again','I’m sorry. Let’s practise together for the next one','I won, so it doesn’t matter'],2,'Respons ini menunjukkan empati dan menawarkan bantuan nyata.');
q('social','Everyday English','Challenger','You need to borrow a ruler. Which request is most polite?',['Give me that now!','Could I borrow your ruler, please?','You must buy me a ruler','Why do you have a ruler?'],1,'Could I …, please? adalah cara meminta izin dengan sopan.');
q('social','Communication & social functions','Champion','“Would you mind closing the window?” Which reply agrees to help?',['Not at all. I’ll close it now','Yes, I refuse to listen','It is a window','I closed my book'],0,'Not at all berarti tidak keberatan, lalu diperjelas dengan tindakan menutup jendela.');
q('social','Everyday English','Explorer','A sign says “Please queue here”. You should …',['run to the front','wait in line','leave your bag behind','speak as loudly as possible'],1,'Queue berarti mengantre atau menunggu dalam barisan.');
q('social','Gratitude','Challenger','Which sentence expresses gratitude for an invitation?',['I appreciate you inviting me','I demand a new invitation','Who broke this chair?','I cannot find my shoes'],0,'I appreciate … menyatakan penghargaan atau rasa terima kasih.');
q('social','Greeting','Challenger','You meet a new classmate for the first time. Choose the best expression.',['Nice to meet you','Welcome back again','Good night and sleep well','See you yesterday'],0,'Nice to meet you digunakan saat berkenalan untuk pertama kali.');
q('logic','Inference & critical thinking','Challenger','What can you reasonably infer?',['It is definitely snowing','It may be raining outside','Raka dislikes school','The umbrella is new'],1,'Payung basah dan sepatu berlumpur mendukung kemungkinan hujan, tetapi tidak memastikan semua detail lain.','Raka entered the classroom carrying a wet umbrella. He wiped his muddy shoes before sitting down.');
q('logic','Language reasoning','Champion','All members of the science club wear blue badges. Mira is a science club member. What must be true?',['Everyone with a blue badge is a club member','Mira wears a blue badge','Mira leads the club','Only Mira has a blue badge'],1,'Aturan berlaku bagi semua anggota, termasuk Mira. Arah sebaliknya tidak otomatis benar.');
q('logic','Inference & critical thinking','Champion','Which claim needs more evidence?',['Ten pupils answered a survey','Seven surveyed pupils liked chess','Every child in the city prefers chess','Some surveyed pupils liked chess'],2,'Survei kecil tidak cukup untuk menyimpulkan preferensi seluruh anak di kota.','Ten pupils in one class answered a survey. Seven said they preferred chess to football.');
q('logic','Language reasoning','Challenger','Ari finished before Bela. Cici finished after Bela. Who finished first?',['Bela','Cici','Ari','Cannot be determined'],2,'Urutannya Ari → Bela → Cici berdasarkan kedua petunjuk.');
q('logic','Inference & critical thinking','Champion','Why did Lila probably wrap the book?',['To keep it clean and dry','To make it heavier for exercise','To stop anyone reading it forever','To change the story'],0,'Awan gelap menunjukkan kemungkinan hujan, sehingga pembungkus membantu melindungi buku.','Lila borrowed a book. Before cycling home, she looked at the dark clouds and wrapped the book in a plastic bag.');
q('logic','Language reasoning','Challenger','Which sentence is an opinion?',['The library opens at nine','The book has 120 pages','This is the most exciting story ever','There are four chairs'],2,'Most exciting adalah penilaian pribadi. Pilihan lain dapat diperiksa secara objektif.');
q('logic','Inference & critical thinking','Champion','Which is the fairest conclusion?',['Music always improves everyone’s scores','Music caused the improvement for certain','The score improved, but other factors may have helped','Studying never affects scores'],2,'Dua perubahan bersamaan tidak membuktikan musik sebagai penyebab tunggal.','Tono listened to music while studying this week and scored higher than last week. He also studied for twice as long.');
q('logic','Language reasoning','Champion','Only pupils with tickets may enter. Dini entered according to the rule. Therefore …',['Dini had a ticket','Dini bought every ticket','Everyone with a ticket entered','Dini performed on stage'],0,'Tiket adalah syarat masuk. Jika Dini masuk sesuai aturan, ia memiliki tiket.');
q('logic','Inference & critical thinking','Challenger','What is the best explanation for Ben’s action?',['He wants to help without embarrassing Jo','He wants to steal a pencil','He thinks the lesson has ended','He wants to leave school'],0,'Melihat Jo mencari pensil lalu memberikan pensil secara diam-diam menunjukkan bantuan yang mempertimbangkan perasaan.','Jo searched his empty pencil case and looked worried. Ben quietly put a spare pencil on Jo’s desk.');
q('logic','Language reasoning','Explorer','Which word best connects these ideas? “Take a jacket ___ it may get cold.”',['although','because','unless','but'],1,'Because memperkenalkan alasan membawa jaket.');
const fox='A fox laughed at a small tortoise for walking slowly. One afternoon, the fox rushed across a narrow bridge with a basket of berries. The basket tipped, and berries rolled into the stream. The tortoise crossed carefully, carrying a few berries at a time. By sunset, she had brought all her berries home. The fox had none left.';
q('stories','Narrative text','Challenger','What is the best lesson from the story?',['Rushing always saves time','Careful, steady effort can succeed','Small animals cannot work hard','Berries grow in streams'],1,'Tortoise berhasil karena sabar dan berhati-hati, sedangkan fox kehilangan hasil akibat terburu-buru.',fox);
q('stories','Narrative text','Explorer','What caused the fox to lose the berries?',['The tortoise ate them','He rushed and the basket tipped','He gave them to a neighbour','It snowed'],1,'Hubungan sebab-akibat tertulis jelas: fox terburu-buru dan keranjangnya miring.',fox);
const trip='Last Saturday, our class visited a coastal village. First, a guide showed us young mangrove trees. Next, we planted seedlings in the soft mud. I lost a shoe, but my friend helped me find it. Before we left, we collected plastic litter along the shore. I returned home tired but proud.';
q('stories','Recount text','Explorer','What is the purpose of this text?',['To retell a past experience','To give a recipe','To advertise shoes','To predict the weather'],0,'Recount menceritakan kembali pengalaman lampau dengan urutan kejadian.',trip);
q('stories','Recount text','Challenger','What happened just before the class left?',['They bought new shoes','They collected plastic litter','They met at school','They planted a forest inland'],1,'Petunjuk “Before we left” diikuti kegiatan mengumpulkan sampah plastik.',trip);
const bio='Dr Hana Putri is a fictional marine scientist. As a child, she loved watching small creatures in rock pools. She later studied biology and developed a low-cost tool for measuring water quality. Instead of keeping the design secret, she shared it with village schools. Today, pupils use her tool to investigate the health of nearby rivers.';
q('stories','Biography','Challenger','Which event happened earliest in Hana’s life?',['She shared a tool design','She studied biology','She watched creatures in rock pools','Pupils used her tool'],2,'As a child menandai masa kanak-kanak, sebelum belajar biologi dan mengembangkan alat.',bio);
q('stories','Biography','Champion','Which trait is best supported by Hana’s actions?',['She is secretive','She is generous with knowledge','She dislikes children','She avoids science'],1,'Membagikan desain kepada sekolah menunjukkan kemurahan hati dalam berbagi ilmu.',bio);
const library='The Willow Library stands beside a quiet canal. Its green wooden door opens into a bright room lined with low bookshelves. Round cushions lie beneath the windows, and a spiral staircase leads to a reading loft. Although the building is small, each corner offers a comfortable place to read.';
q('stories','Descriptive text','Explorer','What is being described?',['A boat','A library','A market','A playground'],1,'Teks menggambarkan ciri dan bagian Willow Library.',library);
q('stories','Descriptive text','Challenger','Which detail suggests the library is welcoming to readers?',['It has uncomfortable stone floors','Every corner offers a comfortable place to read','It is closed all day','It has no windows'],1,'Kenyamanan tempat membaca mendukung kesan ramah bagi pembaca.',library);
q('stories','Narrative text','Champion','Why did the character change her mind?',['She learned that sharing could help everyone','She wanted all the seeds back','She disliked the garden','She forgot how to plant'],0,'Perubahan sikap muncul setelah ia melihat manfaat berbagi.','Nora kept all her seeds in a box. When a neighbour shared some soil with her, she planted a few. The plants produced more seeds than she could use. Next season, Nora gave seeds to every family on her street.');
q('stories','Recount text','Challenger','Which sequence matches the recount?',['Lunch → train → museum','Museum → train → lunch','Train → museum → lunch','Train → lunch → museum'],2,'Penanda first, then, dan after the visit menentukan urutan kejadian.','First, we took a train to the city. Then we explored the history museum. After the visit, we ate lunch in the park.');
