function createStudentSession(api){
  const {$,esc}=api;let selectedRun=null;
  const refs=()=>api.state.reflections||[],findRef=id=>refs().find(r=>r.runId===id),run=id=>api.state.runs.find(r=>r.id===id);
  function tools(){const s=api.session;if(!s)return '';const q=s.questions[s.index],confidence=s.confidences?.[q.id],flag=s.confusedIds?.includes(q.id);return `<section class="student-tools"><div><span class="field-label">Sebelum menjawab: seberapa yakin kamu? <small>(opsional)</small></span><div class="confidence-options" role="group" aria-label="Keyakinan sebelum menjawab"><button class="secondary ${confidence==='sure'?'chosen':''}" data-confidence="sure" aria-pressed="${confidence==='sure'}" ${s.answered||s.interactiveDraft?.path?.length?'disabled':''}>🙂 Yakin</button><button class="secondary ${confidence==='guess'?'chosen':''}" data-confidence="guess" aria-pressed="${confidence==='guess'}" ${s.answered||s.interactiveDraft?.path?.length?'disabled':''}>🤔 Masih menebak</button></div></div><div><button class="text-btn confused-toggle ${flag?'chosen':''}" id="mark-confused" aria-pressed="${!!flag}">${flag?'📌 Ditandai: aku bingung':'📌 Aku bingung di sini'}</button><p class="notice">${s.exam?'Tanda ini dibahas setelah ujian selesai.':'Tandai untuk dibahas lagi setelah sesi.'} Tidak mengubah nilai.</p></div></section>`;}
  function setConfidence(value){const s=api.session;if(!s||s.answered||s.interactiveDraft?.path?.length||!['sure','guess'].includes(value))return;const id=s.questions[s.index].id;s.confidences=s.confidences||{};s.confidences[id]=s.confidences[id]===value?null:value;api.snapshot();document.querySelectorAll('[data-confidence]').forEach(b=>{const chosen=b.dataset.confidence===s.confidences[id];b.classList.toggle('chosen',chosen);b.setAttribute('aria-pressed',String(chosen));});}
  function flag(){const s=api.session;if(!s)return;const id=s.questions[s.index].id;s.confusedIds=s.confusedIds||[];if(s.confusedIds.includes(id))s.confusedIds=s.confusedIds.filter(x=>x!==id);else s.confusedIds.push(id);if(s.answered){const marked=s.confusedIds.includes(id);s.answers[s.index].confused=marked;const a=api.state.attempts.find(a=>a.runId===s.id&&a.id===id);if(a)a.confused=marked;}api.snapshot();const b=$('#mark-confused');b.setAttribute('aria-pressed',String(s.confusedIds.includes(id)));b.classList.toggle('chosen',s.confusedIds.includes(id));b.textContent=s.confusedIds.includes(id)?'📌 Ditandai: aku bingung':'📌 Aku bingung di sini';}
  function lockConfidence(){document.querySelectorAll('[data-confidence]').forEach(b=>b.disabled=true);}
  function form(id){
    const r=run(id);if(!r)return '<p class="empty">Selesaikan satu sesi untuk mulai bercerita.</p>';const existing=findRef(id);if(existing)return saved(existing);
    const answers=api.state.attempts.filter(a=>a.runId===id),marked=new Set(answers.filter(a=>a.confused).map(a=>a.id));
    return `<section class="panel reflection-form" data-reflection-run="${esc(id)}"><div class="title-row"><div><span class="eyebrow">SESI SISWA · CERITA BELAJARKU</span><h2>Bagaimana belajarmu tadi? 💬</h2></div><span class="tag">Opsional · sekitar 1 menit</span></div><p>${esc(r.title)} · ${esc(r.date)}</p><p class="sharing-note">Jawaban survei dan ceritamu bisa dilihat orang tua pada profil ini. Ceritakan bagian belajarnya; kamu boleh melewati survei.</p><fieldset><legend>1. Bagaimana rasanya tadi?</legend><div class="survey-moods">${StudentModel.moods.map(([v,emoji,label])=>`<label class="survey-choice"><input type="radio" name="student-mood" value="${v}"><span>${emoji} ${label}</span></label>`).join('')}</div></fieldset><fieldset><legend>2. Bagian mana yang terasa sulit? <small>Boleh lebih dari satu.</small></legend><div class="survey-checks">${StudentModel.difficulties.map(([v,label])=>`<label class="survey-choice"><input type="checkbox" name="student-difficulty" value="${v}"><span>${label}</span></label>`).join('')}</div></fieldset><details class="question-picker" ${marked.size?'open':''}><summary>Tandai soal tertentu (opsional) · ${marked.size} tanda dari sesi</summary><div class="survey-question-list">${answers.map((a,i)=>{const q=QUESTIONS.find(q=>q.id===a.id);return `<label class="survey-choice"><input type="checkbox" name="student-question" value="${esc(q.id)}" ${marked.has(q.id)?'checked':''}><span><b>Soal ${i+1} · ${q.level} · ${esc(q.tag)}</b><br>${esc(q.prompt)}${a.confidence==='guess'?'<small> · Kamu memilih “Masih menebak”</small>':''}</span></label>`;}).join('')}</div></details><fieldset><legend>3. Bantuan apa yang kamu inginkan?</legend><div class="survey-checks">${StudentModel.helps.map(([v,label])=>`<label class="survey-choice"><input type="radio" name="student-help" value="${v}"><span>${label}</span></label>`).join('')}</div></fieldset><label class="field-label" for="student-note">Ada yang ingin kamu ceritakan? <small>(opsional)</small></label><textarea id="student-note" maxlength="1500" rows="3" placeholder="Misalnya: Aku tahu arti katanya, tetapi bingung memilih jawaban yang paling tepat."></textarea><p class="notice">Pilih juga bagian yang sulit di atas agar latihan berikutnya bisa menyesuaikan. Cerita bebas disimpan apa adanya untuk dibaca bersama orang tua.</p><p id="student-error" role="alert"></p><div class="milestone-actions"><button class="primary" id="save-reflection" data-run="${esc(id)}">Simpan cerita & lihat bantuan →</button><button class="text-btn" id="skip-reflection" data-run="${esc(id)}">Lewati dulu</button></div><p class="notice">Survei tersimpan setelah menekan Simpan. Mengisi atau melewatinya tidak menambah atau mengurangi XP.</p></section>`;
  }
  function lesson(ref,plan){
    if(!plan.questions.length)return '';
    const topics=[...new Set(plan.questions.map(q=>q.topic))].slice(0,2);
    return `<div class="mini-lessons">${topics.map(t=>{const [title,example,text]=StudentModel.examples[t];return `<article class="mini-lesson"><b>${esc(title)}</b><div class="passage">${esc(example)}</div><p>${esc(text)}</p></article>`;}).join('')}</div><div class="support-steps"><span>1. Baca contoh di atas</span><span>2. Coba ${plan.questions.length} soal</span><span>3. Gunakan petunjuk bila perlu</span></div><button class="primary" data-start="support:${esc(ref.runId)}">Mulai latihan tindak lanjut · ${plan.questions.length} soal →</button>`;
  }
  function saved(ref){const r=run(ref.runId),plan=StudentModel.support(api.state,ref,QUESTIONS),due=StudentModel.dueDate(ref);return `<section class="panel reflection-saved"><span class="eyebrow">CERITAMU TERSIMPAN</span><h2>Terima kasih sudah bercerita 🌱</h2><p>${esc(r?.title||'Sesi belajar')} · ${StudentModel.label(StudentModel.moods,ref.mood)}</p><div class="chips">${ref.difficulties.map(d=>`<span class="chip">${esc(StudentModel.label(StudentModel.difficulties,d))}</span>`).join('')}</div><h3>${esc(plan.title)}</h3><p>${esc(plan.text)}</p>${lesson(ref,plan)}${due?`<p class="notice">Kita cek kembali pada ${due}. Kamu tetap boleh belajar atau beristirahat sesuai kebutuhan.</p>`:'<p class="notice">Ceritamu tercatat di Sesi Siswa dan Ruang Orang Tua.</p>'}<button class="text-btn" data-page="student">Lihat semua cerita →</button></section>`;}
  function checks(){const due=refs().filter(r=>{const d=StudentModel.dueDate(r);return d&&d<=api.dateKey();});return due.length?`<div class="section-head"><h2>Bagaimana sekarang?</h2></div><div class="checkin-grid">${due.map(r=>`<section class="panel checkin-card"><h3>Kita cek kembali bersama 🌱</h3><p>Pada ${r.date}, kamu bercerita tentang ${esc(StudentModel.label(StudentModel.difficulties,r.difficulties[0]))} di sesi ${esc(run(r.runId)?.title||'belajar')}.</p><p>Setelah beberapa hari, bagaimana rasanya?</p><div class="milestone-actions">${StudentModel.followups.map(([v,label])=>`<button class="secondary" data-checkin="${v}" data-ref="${esc(r.runId)}">${label}</button>`).join('')}</div></section>`).join('')}</div>`:'';}
  function student(){
    if(selectedRun&&!run(selectedRun))selectedRun=null;
    const runs=[...api.state.runs].reverse(),unfilled=runs.filter(r=>!findRef(r.id)),latest=selectedRun?run(selectedRun):unfilled.find(r=>!(api.state.skippedReflections||[]).includes(r.id));
    return `<h1>Cerita belajarku 💬</h1><p class="sub">Bukan cuma nilaimu yang penting. Ceritakan apa yang mudah, apa yang sulit, dan bantuan yang kamu inginkan.</p>${checks()}${runs.length?`<div class="filters"><label for="reflection-session">Pilih sesi untuk diceritakan</label><select id="reflection-session"><option value="">Pilih sesi…</option>${runs.map(r=>`<option value="${esc(r.id)}" ${latest?.id===r.id?'selected':''}>${esc(r.title)} · ${r.date}${findRef(r.id)?' · Sudah diisi':(api.state.skippedReflections||[]).includes(r.id)?' · Dilewati':''}</option>`).join('')}</select></div><div id="reflection-content">${latest?form(latest.id):'<section class="panel"><p>Kamu boleh mengisi survei sesi yang pernah dilewati lewat pilihan di atas, atau melanjutkan petualangan.</p></section>'}</div>`:'<section class="panel empty">Selesaikan daily, latihan, atau ujian. Setelah itu, kamu bisa bercerita di sini.</section>'}<div class="section-head"><h2>Jejak ceritaku</h2><span class="tag">${refs().length} survei tersimpan</span></div>${history(false)}`;
  }
  function history(parent){const list=[...refs()].reverse().slice(0,20);return list.length?`<div class="reflection-history">${list.map(ref=>{const r=run(ref.runId),e=StudentModel.evidence(api.state,ref.runId),last=ref.checkins?.at(-1);return `<article class="panel reflection-entry"><div class="title-row"><h3>${esc(r?.title||'Sesi belajar')}</h3><span class="tag">Survei ${ref.date}</span></div><p class="notice">Tanggal latihan: ${esc(r?.date||'—')} · Tingkat: ${[...new Set(api.state.attempts.filter(a=>a.runId===ref.runId).map(a=>QUESTIONS.find(q=>q.id===a.id).level))].join(' / ')||'—'}</p><div class="reflection-columns"><div><b>Yang ${parent?'anak':'kamu'} rasakan</b><p>${StudentModel.label(StudentModel.moods,ref.mood)}</p><div class="chips">${ref.difficulties.map(d=>`<span class="chip">${esc(StudentModel.label(StudentModel.difficulties,d))}</span>`).join('')}</div><p>Bantuan dipilih: <b>${esc(StudentModel.label(StudentModel.helps,ref.help))}</b></p>${ref.note?`<blockquote>${esc(ref.note)}</blockquote>`:''}</div><div><b>Hasil sesi yang tercatat</b><p>${r?.correct??e.correct}/${r?.total??e.answered} jawaban benar · ${e.flagged} soal ditandai bingung.<br>${e.guessedCorrect} jawaban benar sambil menebak.<br>${e.sureWrong} jawaban belum tepat meskipun yakin.</p><p class="notice">${e.confidenceResponses}/${e.answered} jawaban memiliki pilihan keyakinan. Perasaan dan hasil bukan ukuran yang sama.</p>${ref.questionIds.length?`<details><summary>${ref.questionIds.length} soal pilihan siswa</summary>${ref.questionIds.map(id=>{const q=QUESTIONS.find(q=>q.id===id);return `<p><b>${q.level} · ${esc(q.tag)}</b><br>${esc(q.prompt)}</p>`;}).join('')}</details>`:''}</div></div>${last?`<p class="checkin-answer">Cek kembali ${last.date}: ${esc(StudentModel.label(StudentModel.followups,last.feeling))}</p>`:''}<button class="text-btn" data-survey="${esc(ref.runId)}">Lihat bantuan untuk sesi ini →</button></article>`;}).join('')}</div><p class="notice">Menampilkan hingga 20 cerita terbaru. Semua cerita tetap ada di cadangan profil.</p>`:'<section class="panel empty">Belum ada survei tersimpan. Pilihan keyakinan dan tanda bingung tetap tercatat pada jawaban.</section>';}
  function parentPanel(){
    const recent=refs().filter(r=>r.date>=EQ.addDays(api.dateKey(),-6)&&r.date<=api.dateKey()),counts=StudentModel.difficulties.filter(([id])=>id!=='none').map(([id,label])=>({id,label,count:recent.filter(r=>r.difficulties.includes(id)).length})).filter(x=>x.count).sort((a,b)=>b.count-a.count);
    const answers=api.state.attempts.filter(a=>a.date>=EQ.addDays(api.dateKey(),-6)&&a.date<=api.dateKey()),guessed=answers.filter(a=>a.correct&&a.confidence==='guess').length,sureWrong=answers.filter(a=>!a.correct&&a.confidence==='sure').length,flags=answers.filter(a=>a.confused).length;
    return `<div class="section-head"><h2>Suara siswa: yang dirasakan & yang tercatat</h2></div><section class="panel student-parent-summary"><p>${recent.length} survei dalam 7 hari terakhir. Kesulitan di bawah berasal dari pilihan anak, bukan kesimpulan otomatis dari cerita bebas.</p><div class="chips">${counts.length?counts.map(c=>`<span class="chip">${esc(c.label)} · ${c.count} sesi</span>`).join(''):'<span class="chip">Belum ada kesulitan yang dilaporkan minggu ini</span>'}</div><p>${guessed} jawaban benar sambil menebak · ${sureWrong} jawaban belum tepat meski yakin · ${flags} tanda bingung.</p><p class="notice">Pilihan keyakinan bersifat opsional. Gunakan pola ini untuk membuka percakapan, bukan memberi label pada anak. Cerita dan survei berada pada profil yang sedang dipilih.</p></section>${history(true)}`;
  }
  function widget(){const due=refs().filter(r=>{const d=StudentModel.dueDate(r);return d&&d<=api.dateKey();}).length;return `<section class="panel student-invite"><div><h2>Ada yang ingin kamu ceritakan? 💬</h2><p>${due?`${due} cerita siap dicek kembali. Bagaimana rasanya sekarang?`:'Setelah belajar, ceritakan bagian yang sulit agar bantuan berikutnya lebih sesuai.'}</p></div><button class="secondary" data-page="student">Buka Sesi Siswa →</button></section>`;}
  function click(b){
    if(b.dataset.confidence){setConfidence(b.dataset.confidence);return true;}
    if(b.id==='mark-confused'){flag();return true;}
    if(b.dataset.survey){selectedRun=b.dataset.survey;api.navigate('student');return true;}
    if(b.id==='skip-reflection'){api.state.skippedReflections=api.state.skippedReflections||[];if(!api.state.skippedReflections.includes(b.dataset.run))api.state.skippedReflections.push(b.dataset.run);if(!api.save())return true;selectedRun=null;const container=b.closest('.reflection-form');if(container)container.outerHTML='<section class="panel"><p>Survei dilewati. Kamu bisa mengisinya nanti melalui Sesi Siswa. Progres latihan tetap tersimpan.</p><button class="text-btn" data-page="student">Buka Sesi Siswa →</button></section>';return true;}
    if(b.id==='save-reflection'){
      const container=b.closest('.reflection-form'),selected=name=>[...container.querySelectorAll('input[name="'+name+'"]:checked')].map(x=>x.value),mood=selected('student-mood')[0],difficulties=selected('student-difficulty'),help=selected('student-help')[0],note=container.querySelector('#student-note').value.trim(),questionIds=selected('student-question');
      if(!mood||!difficulties.length||!help){container.querySelector('#student-error').textContent='Pilih perasaan, bagian yang sulit (atau Tidak ada kesulitan), dan bantuan yang kamu inginkan. Cerita bebas boleh kosong.';return true;}
      try{const ref=StudentModel.create(api.state,b.dataset.run,{mood,difficulties,help,note,questionIds},api.dateKey(),QUESTIONS);api.state.reflections=api.state.reflections||[];api.state.reflections.push(ref);api.state.skippedReflections=(api.state.skippedReflections||[]).filter(id=>id!==ref.runId);if(!api.save()){api.state.reflections=api.state.reflections.filter(r=>r!==ref);container.querySelector('#student-error').textContent='Survei belum tersimpan. Jangan tutup halaman; coba Simpan lagi.';return true;}container.outerHTML=saved(ref);api.toast('Ceritamu tersimpan. Terima kasih sudah memberi tahu.');}
      catch(e){container.querySelector('#student-error').textContent=e.message;}return true;
    }
    if(b.dataset.checkin){try{const ref=findRef(b.dataset.ref);if(!ref)return true;const next=StudentModel.checkIn(ref,b.dataset.checkin,api.dateKey());api.state.reflections=refs().map(r=>r===ref?next:r);if(!api.save()){api.state.reflections=refs().map(r=>r===next?ref:r);return true;}api.navigate('student');api.toast('Terima kasih. Perubahan yang kamu rasakan sudah tercatat.');}catch(e){api.toast(e.message);}return true;}
    return false;
  }
  function change(e){if(e.target.name==='student-difficulty'&&e.target.checked){const all=document.querySelectorAll('input[name="student-difficulty"]');all.forEach(x=>{if(e.target.value==='none'&&x!==e.target)x.checked=false;else if(e.target.value!=='none'&&x.value==='none')x.checked=false;});return true;}if(e.target.id==='reflection-session'){selectedRun=e.target.value||null;$('#reflection-content').innerHTML=selectedRun?form(selectedRun):'<section class="panel"><p>Pilih satu sesi di atas untuk mulai bercerita.</p></section>';return true;}return false;}
  function customMode(mode){if(!mode.startsWith('support:'))return null;const ref=findRef(mode.slice(8));if(!ref)return {error:'Cerita sesi ini belum ditemukan.'};const plan=StudentModel.support(api.state,ref,QUESTIONS);return plan.questions.length?{questions:plan.questions,title:'Tindak lanjut · '+plan.title,planReasons:Object.fromEntries(plan.questions.map(q=>[q.id,'Dipilih dari surveimu: kita pahami '+q.tag+' selangkah demi selangkah.']))}:{error:plan.text};}
  return {student,tools,setConfidence,flag,lockConfidence,form,parentPanel,widget,click,change,customMode,reset(){selectedRun=null;}};
}
